In [1]:
# !pip install spacy
# !python -m spacy download pt_core_news_lg

In [2]:
import pandas as pd
import spacy
from typing import Literal
from spacy.matcher import Matcher
from spacy.tokens import Doc

In [3]:
brasileiras_file_path = 'data/corpus-musicas-brasileiras.csv'
spotify_file_path = 'data/spotify-famosas.csv'

In [4]:
brasileiras_df = pd.read_csv(brasileiras_file_path)
spotify_df = pd.read_csv(spotify_file_path)

In [5]:
#Renomear as colunas para nomes simples
brasileiras_df.columns = ['nome', 'artista', 'genero', 'letra']
brasileiras_df

,nome,artista,genero,letra
0,Carolina,Seu Jorge,MPB,Carolina é uma menina bem difícil de esquecer ...
1,Epitáfio,Titãs,Rock,Devia ter amado mais Ter chorado mais Ter vist...
2,Lugar Ao Sol,Charlie Brown Jr.,Rock,"Que bom viver, como é bom sonhar E o que ficou..."
3,Relicário - Ao Vivo,Cássia Eller,Rock,É uma índia com colar A tarde linda que não qu...
4,Você Me Vira A Cabeça (Me Tira Do Sério),Alcione,Samba,"Você me vira a cabeça, me tira do sério Destró..."
...,...,...,...,...
146607,Hino 96 - a Chave de Ser,Xamã Gideon dos Lakotas,World Music,Esclarecimentos Maiores\nEntrego agora a chave...
146608,Hino 97 - Invocação,Xamã Gideon dos Lakotas,World Music,Invocação Eu Sou\nEu Sou a presença Divina Eu ...
146609,Hino 98 - Conhecimentos,Xamã Gideon dos Lakotas,World Music,Aqui na fazenda ensinamos a você todo conhecim...
146610,Chove Chuva,Miriam Makeba,World Music; Black Music; Blues,Chove chuva\nChove sem parar\nChove chuva\nCho...
146611,Mas Que Nada,Miriam Makeba,World Music; Black Music; Blues,O ariá raió\nObá obá obá\n\nMas que nada\nSai ...

In [6]:
spotify_df.columns = ['nome', 'artista', 'ano', 'genero', 'letra', 'playlist']
spotify_df.drop(columns=['ano', 'playlist'], inplace=True)
spotify_df

,nome,artista,genero,letra
0,Carolina,Seu Jorge,MPB,Carolina é uma menina bem difícil de esquecer ...
1,Epitáfio,Titãs,Rock,Devia ter amado mais Ter chorado mais Ter vist...
2,Lugar Ao Sol,Charlie Brown Jr.,Rock,"Que bom viver, como é bom sonhar E o que ficou..."
3,Relicário - Ao Vivo,Cássia Eller,Rock,É uma índia com colar A tarde linda que não qu...
4,Você Me Vira A Cabeça (Me Tira Do Sério),Alcione,Samba,"Você me vira a cabeça, me tira do sério Destró..."
...,...,...,...,...
1622,Carinha de Neném,Japãozin,Piseiro,É o Japãozin da Cachoeira meu patrão É o Japão...
1623,Zero Saudade - Ao Vivo,Os Barões Da Pisadinha,Piseiro,Meu coração desativou você Faz tempo que eu nã...
1624,Meia Noite,Zé Vaqueiro,Piseiro,Você vai deixar a porta aberta para o nosso en...
1625,Recairei - Ao Vivo,Os Barões Da Pisadinha,Piseiro,Já faz uma semana que eu tô limpo de você Iê i...
1626,Se Namorar Fosse Bom - Ao Vivo,Os Barões Da Pisadinha,Piseiro,Tá todo mundo dizendo Tá na hora de casar Vira...

In [7]:
final_df = pd.concat([brasileiras_df, spotify_df], ignore_index=True)
final_df['music_id'] = final_df.index + 1
final_df

,nome,artista,genero,letra,music_id
0,Carolina,Seu Jorge,MPB,Carolina é uma menina bem difícil de esquecer ...,1
1,Epitáfio,Titãs,Rock,Devia ter amado mais Ter chorado mais Ter vist...,2
2,Lugar Ao Sol,Charlie Brown Jr.,Rock,"Que bom viver, como é bom sonhar E o que ficou...",3
3,Relicário - Ao Vivo,Cássia Eller,Rock,É uma índia com colar A tarde linda que não qu...,4
4,Você Me Vira A Cabeça (Me Tira Do Sério),Alcione,Samba,"Você me vira a cabeça, me tira do sério Destró...",5
...,...,...,...,...,...
148234,Carinha de Neném,Japãozin,Piseiro,É o Japãozin da Cachoeira meu patrão É o Japão...,148235
148235,Zero Saudade - Ao Vivo,Os Barões Da Pisadinha,Piseiro,Meu coração desativou você Faz tempo que eu nã...,148236
148236,Meia Noite,Zé Vaqueiro,Piseiro,Você vai deixar a porta aberta para o nosso en...,148237
148237,Recairei - Ao Vivo,Os Barões Da Pisadinha,Piseiro,Já faz uma semana que eu tô limpo de você Iê i...,148238
148238,Se Namorar Fosse Bom - Ao Vivo,Os Barões Da Pisadinha,Piseiro,Tá todo mundo dizendo Tá na hora de casar Vira...,148239

In [8]:
final_df.to_csv('data/corpus-musicas.csv', index=False)

In [9]:
import re
#Função para remover caracteres especiais e substituir quebras de linha por ponto
def preprocessar_texto(texto):
    texto = str(texto)  # Garantir que o texto é uma string

    # 1) Substituir quebras de linha únicas por ". "
    texto = re.sub(r"\n(?!\n)", ". ", texto)

    # 2) Injetar ". " entre letra minúscula (incluindo acentos) + espaço + letra maiúscula
    pattern = (
        r'(?<=[a-záàâãéèêíîóôõúûç])'  # atrás: letra minúscula (com acentos)
        r'\s+'                        # um ou mais espaços
        r'(?=[A-ZÁÀÂÃÉÈÊÍÎÓÔÕÚÛÇ])'   # à frente: letra maiúscula (com acentos)
    )
    texto = re.sub(pattern, '. ', texto)

    # 3) Garantir ponto final no fim do texto
    if not texto.endswith('.'):
        texto += '.'

    return texto

final_df['letra_preprocessada'] = final_df['letra'].apply(preprocessar_texto) 
final_df

,nome,artista,genero,letra,music_id,letra_preprocessada
0,Carolina,Seu Jorge,MPB,Carolina é uma menina bem difícil de esquecer ...,1,Carolina é uma menina bem difícil de esquecer....
1,Epitáfio,Titãs,Rock,Devia ter amado mais Ter chorado mais Ter vist...,2,Devia ter amado mais. Ter chorado mais. Ter vi...
2,Lugar Ao Sol,Charlie Brown Jr.,Rock,"Que bom viver, como é bom sonhar E o que ficou...",3,"Que bom viver, como é bom sonhar. E o que fico..."
3,Relicário - Ao Vivo,Cássia Eller,Rock,É uma índia com colar A tarde linda que não qu...,4,É uma índia com colar. A tarde linda que não q...
4,Você Me Vira A Cabeça (Me Tira Do Sério),Alcione,Samba,"Você me vira a cabeça, me tira do sério Destró...",5,"Você me vira a cabeça, me tira do sério. Destr..."
...,...,...,...,...,...,...
148234,Carinha de Neném,Japãozin,Piseiro,É o Japãozin da Cachoeira meu patrão É o Japão...,148235,É o. Japãozin da. Cachoeira meu patrão. É o. J...
148235,Zero Saudade - Ao Vivo,Os Barões Da Pisadinha,Piseiro,Meu coração desativou você Faz tempo que eu nã...,148236,Meu coração desativou você. Faz tempo que eu n...
148236,Meia Noite,Zé Vaqueiro,Piseiro,Você vai deixar a porta aberta para o nosso en...,148237,Você vai deixar a porta aberta para o nosso en...
148237,Recairei - Ao Vivo,Os Barões Da Pisadinha,Piseiro,Já faz uma semana que eu tô limpo de você Iê i...,148238,Já faz uma semana que eu tô limpo de você. Iê ...
148238,Se Namorar Fosse Bom - Ao Vivo,Os Barões Da Pisadinha,Piseiro,Tá todo mundo dizendo Tá na hora de casar Vira...,148239,Tá todo mundo dizendo. Tá na hora de casar. Vi...

In [10]:
final_df.to_csv('data/corpus-musicas-final.csv', index=False)

In [11]:
print(final_df['letra_preprocessada'].iloc[0])

Carolina é uma menina bem difícil de esquecer. Andar bonito e um brilho no olhar. Tem um jeito adolescente que me faz enlouquecer. E um molejo que eu não vou te enganar. Maravilha feminina, meu docinho de pavê. Inteligente, ela é muito sensual. Te confesso que estou apaixonado por você. Ô, Carolina, isso é muito natural. Ô, Carolina, eu preciso de você. Ô, Carolina, eu não vou suportar não te ver. Carolina, eu preciso te falar. Ô, Carolina, eu vou amar você. De segunda a segunda, fico louco pra te ver. Quando eu te ligo, você quase nunca está. Isso era outra coisa que eu queria te dizer. Não temos tempo, então melhor deixar pra lá. A princípio, no domingo, o que você quer fazer? Faça um pedido, que eu irei realizar. Olha aí, amigo, eu digo que ela só me dá prazer. Essa mina. Carolina é de abalar, oi. Ô, Carolina, eu preciso de você. Ô, Carolina, eu não vou suportar não te ver. Carolina, eu preciso te falar. Ô, Carolina eu vou amar você. Carolina, Carolina. Carolina, preciso te encontrar. Carolina, me sinto muito só. Carolina, preciso te dizer. Ô, Carolina, eu só quero amar você. Carolina, preciso te encontrar. Ô, Carolina, me sinto muito só. Carolina, preciso te dizer. Ô, Carolina, eu só quero amar você. Carolina é uma menina bem difícil de esquecer. Andar bonito e um brilho no olhar. Tem um jeito adolescente que me faz enlouquecer. E um molejo que eu não vou te enganar. Maravilha feminina, meu docinho de pavê. Inteligente, ela é muito sensual. Te confesso que estou apaixonado por você. Ô, Carolina, isso é muito natural. Ô, Carolina, eu preciso de você. Ô, Carolina, não vou suportar não te ver. Carolina, eu preciso te falar. Ô, Carolina, eu vou amar você. Eu vou amar você. Pois eu vou te dar muito carinho. Vou te dar beijinho no cangote. Oi, Carolina. Menina bela, menina bela. Maravilha feminina. Carolina, preciso te encontrar. Carolina, me sinto muito só. Carolina, preciso te dizer. Ô, Carolina, eu só quero amar você. Carolina, preciso te encontrar. Ô, Carolina, me sinto muito só. Carolina, preciso te dizer. Ô, Carolina, eu só quero amar você. Ô, Carolina, preciso te encontrar. Ô, Carolina, me sinto muito só. Ô, Carolina, preciso te dizer. Ô, Carolina, eu só quero amar você. Ô, Carolina, ô, Carolina (ô, Carolina) Ô, Carolina, ô, Carolina. Carol, Carol, Carol, Carol, Carol. Carol, Carol, Carol. Carol, Carol, Carol, Carol, Carol. Carol, Carol, Carol (ô, Carolina) Carol, Carol, Carol, Carol, Carol. Carol, Carol, Carol. Carol, Carol, Carol, Carol, Carol. Carol, Carol, Carol.

In [12]:
print(final_df.iloc[10000]['letra_preprocessada'])

Sinto que você está dividida. Entre ele e eu. Não sabe o que é melhor pra sua vida. Se é ele ou eu. Vejo que esta dúvida lhe cala. Toda vez que alguém vai lhe perguntar. Quem mais lhe agrada. Nem eu mesmo sei. Eu já fiz de tudo para entender. O que me faz tão parecido assim com ele. O que me falta que você procure nele. O que que eu tenho que ele ainda não lhe deu. Diga qual dos dois tem mais ciúme. O que mais sofre quando você vai embora. Eu só lhe digo que se tem um que lhe adora. Esse alguém sou eu. Se ele tem seus beijos, seus carinhos,. Também tenho eu. Se ele chora quando está sozinho. Também choro eu. Acho que devemos dar um jeito nessa situação. Dois amores dentro do seu peito, e um só coração.

In [13]:
#Quebrando a letra_preprocessada em frases e criando um novo dataframe. Cada música será identificada por seu music_id
def quebrar_em_frases(letra):
    # Usando regex para dividir a letra em frases
    frases = re.split(r'(?<=[.!?]) +', letra)
    return frases

# Iterar sobre cada música e suas letras
all_frases = []
for index, row in final_df.iterrows():
    music_id = row['music_id']
    letra = row['letra_preprocessada']
    # Quebrar a letra em frases
    frases = quebrar_em_frases(letra)
    # Remover frases vazias
    frases = [frase.strip() for frase in frases if frase.strip()]
    for i, frase in enumerate(frases):
        # Adicionar a frase ao DataFrame
        all_frases.append({'music_id': music_id, 'music_frase_id': i + 1, 'frase': frase})
frases_df = pd.DataFrame(all_frases)
frases_df['frase_id'] = frases_df.index + 1

frases_df

,music_id,music_frase_id,frase,frase_id
0,1,1,Carolina é uma menina bem difícil de esquecer.,1
1,1,2,Andar bonito e um brilho no olhar.,2
2,1,3,Tem um jeito adolescente que me faz enlouquecer.,3
3,1,4,E um molejo que eu não vou te enganar.,4
4,1,5,"Maravilha feminina, meu docinho de pavê.",5
...,...,...,...,...
4643921,148239,56,Se eu pego o mundo inteiro.,4643922
4643922,148239,57,Se namorar fosse bom.,4643923
4643923,148239,58,Ninguém tava solteiro.,4643924
4643924,148239,59,Pra quê pegar só uma.,4643925
4643925,148239,60,Se eu pego o mundo inteiro.,4643926

In [14]:
filtered_frases_df = frases_df.copy()
#Remove frases vazias ou que não possuem letras
filtered_frases_df = filtered_frases_df[filtered_frases_df['frase'].str.strip().astype(bool)]
filtered_frases_df = filtered_frases_df[filtered_frases_df['frase'].str.len() > 0]
filtered_frases_df = filtered_frases_df[filtered_frases_df['frase'].str.contains(r'[a-zA-Z]')]

#Remover frases duplicadas
filtered_frases_df = filtered_frases_df.drop_duplicates(subset=['frase'], keep='first')
filtered_frases_df = filtered_frases_df.reset_index(drop=True)
filtered_frases_df

,music_id,music_frase_id,frase,frase_id
0,1,1,Carolina é uma menina bem difícil de esquecer.,1
1,1,2,Andar bonito e um brilho no olhar.,2
2,1,3,Tem um jeito adolescente que me faz enlouquecer.,3
3,1,4,E um molejo que eu não vou te enganar.,4
4,1,5,"Maravilha feminina, meu docinho de pavê.",5
...,...,...,...,...
2685690,146609,480,Recite as afirmações por 10 minutos ininterrup...,4574304
2685691,146611,4,Chove sem parar\n.,4574434
2685692,146611,10,De molhar o meu divino amor\n.,4574440
2685693,146611,14,Inocente como a flor\n.,4574444
2685694,146611,18,O meu amor assim\n.,4574448

In [15]:
pln = spacy.load('pt_core_news_lg')
pln

In [16]:
def define_pattern(subject_array, gender: Literal["Masc", "Fem"]):
  matcher = Matcher(vocab=pln.vocab)
  gender_morph = f"Gender={gender}|Number=Sing"

  #Sujeitos pré definidos
  sujeitoauxadjetivo = [
    {'LOWER': {'IN': subject_array}},  # Sujeito feminino
    {'POS': 'ADV', 'OP': '?'},  # Provavelmente etc
    {'POS': 'ADV', 'OP': '?'},  # Negação
    {"POS":"VERB", 'OP': '?'},
    {'POS': 'AUX',  'OP': '?'},  # Verbo auxiliar
    {"POS":"VERB", 'OP': '?'},
    {'POS': 'AUX', 'OP': '?'},  # Verbo auxiliar para casos do tipo ela está ficando
    {'POS': 'ADV', 'OP': '?'},  # Realmente / Provavelmente
    {'POS': 'ADV', 'OP': '?'},  # Muito / Pouco
    {'POS': {'IN': ['ADJ']}},  # Adjetivo
    {'POS': {'IN': ['ADP', 'SCONJ', 'PART']}, 'OP': '?'},  # Preposição, conjunção ou partícula opcional (ex: "de", "que", "para")
    {'POS': 'DET', 'OP': '?'},  # Determinante opcional (ex: "um", "uma", "o", "a")
    {'POS': {'IN': ['NOUN', 'ADJ']}, 'OP': '?'},  # Substantivo opcional (ex: "marra", "casa", "guerreiro")
    {'POS': 'VERB', 'MORPH': 'VerbForm=Inf', 'OP': '?'},  # Verbo no infinitivo opcional (ex: "viajar", "falar")
  ]

  sujeitoauxsubst = [
    {'LOWER': {'IN': subject_array}},  # Sujeito feminino
    {'POS': 'ADV', 'OP': '?'},  # Provavelmente etc
    {'POS': 'ADV', 'OP': '?'},  # Negação
    {'POS': 'AUX'},  # Verbo auxiliar
    {'POS': 'AUX', 'OP': '?'},  # Verbo auxiliar para casos do tipo ela está ficando
    {'POS': 'DET', 'OP': '?'},  # Determinante opcional (ex: "um", "uma", "o", "a")
    {'POS': 'ADV', 'OP': '?'},  # Realmente / Provavelmente
    {'POS': 'ADV', 'OP': '?'},  # Muito / Pouco
    {'POS': {'IN': ['NOUN']}, "MORPH": {"IN": [gender_morph]}},  # Substantivo
    {'POS': {'IN': ['ADP', 'SCONJ', 'PART']}, 'OP': '?'},  # Preposição, conjunção ou partícula opcional (ex: "de", "que", "para")
    {'POS': 'DET', 'OP': '?'},  # Determinante opcional (ex: "um", "uma", "o", "a")
    {'POS': {'IN': ['NOUN', 'ADJ']}, 'OP': '?'},  # Substantivo opcional (ex: "marra", "casa", "guerreiro")
    {'POS': 'VERB', 'MORPH': 'VerbForm=Inf', 'OP': '?'},  # Verbo no infinitivo opcional (ex: "viajar", "falar")
  ]

  sujeitoauxverbo = [
    {'LOWER': {'IN': subject_array}},  # Sujeito feminino
    {'POS': 'ADV', 'OP': '?'},  # Provavelmente etc
    {'POS': 'ADV', 'OP': '?'},  # Negação
    {"POS":"VERB", 'OP': '?'},
    {'POS': 'AUX',  'OP': '?'},  # Verbo auxiliar
    {"POS":"VERB", 'OP': '?'},
    {'POS': 'AUX', 'OP': '?'},  # Verbo auxiliar para casos do tipo ela está ficando
    {'POS': 'ADV', 'OP': '?'},  # Realmente / Provavelmente
    {'POS': 'ADV', 'OP': '?'},  # Muito / Pouco
    {'POS': 'VERB', 'MORPH': {'IN': [f"{gender_morph}|VerbForm=Part|Voice=Pass"]}},  # Verbo na Voz Passiva
    {'POS': {'IN': ['ADP', 'SCONJ', 'PART']}, 'OP': '?'},  # Preposição, conjunção ou partícula opcional (ex: "de", "que", "para")
    {'POS': 'DET', 'OP': '?'},  # Determinante opcional (ex: "um", "uma", "o", "a")
    {'POS': {'IN': ['NOUN', 'ADJ']}, 'OP': '?'},  # Substantivo opcional (ex: "marra", "casa", "guerreiro")
    {'POS': 'VERB', 'MORPH': 'VerbForm=Inf', 'OP': '?'},  # Verbo no infinitivo opcional (ex: "viajar", "falar")
  ]

  #Nome Próprio
  nomeauxproprio = [
      {"ENT_TYPE": "PER",'POS': 'PROPN', "MORPH": {"IN": [gender_morph]}},
      {'POS': 'ADV', 'OP': '?'},  # Provavelmente etc
      {'POS': 'ADV', 'OP': '?'},  # Negação
      {"POS":"VERB", 'OP': '?'},
      {'POS': 'AUX'},  # Verbo auxiliar
      {"POS":"VERB", 'OP': '?'},
      {'POS': 'AUX', 'OP': '?'},  # Verbo auxiliar para casos do tipo ela está ficando
      {'POS': 'ADV', 'OP': '?'},  # Realmente / Provavelmente
      {'POS': 'ADV', 'OP': '?'},  # Muito / Pouco
      {'POS': {'IN': ['ADJ']}},  # Adjetivo
      {'POS': {'IN': ['ADP', 'SCONJ', 'PART']}, 'OP': '?'},  # Preposição, conjunção ou partícula opcional (ex: "de", "que", "para")
      {'POS': 'DET', 'OP': '?'},  # Determinante opcional (ex: "um", "uma", "o", "a")
      {'POS': {'IN': ['NOUN', 'ADJ']}, 'OP': '?'},  # Substantivo opcional (ex: "marra", "casa", "guerreiro")
      {'POS': 'VERB', 'MORPH': 'VerbForm=Inf', 'OP': '?'},  # Verbo no infinitivo opcional (ex: "viajar", "falar")
  ]


  nomeauxsubst = [
      {"ENT_TYPE": "PER",'POS': 'PROPN', "MORPH": {"IN": [gender_morph]}},
      {'POS': 'ADV', 'OP': '?'},  # Provavelmente etc
      {'POS': 'ADV', 'OP': '?'},  # Negação
      {'POS': 'AUX'},  # Verbo auxiliar
      {'POS': 'AUX', 'OP': '?'},  # Verbo auxiliar para casos do tipo ela está ficando
      {'POS': 'ADV', 'OP': '?'},  # Realmente / Provavelmente
      {'POS': 'ADV', 'OP': '?'},  # Muito / Pouco
      {'POS': {'IN': ['NOUN']}, "MORPH": {"IN": [gender_morph]}},  # Substantivo
      {'POS': {'IN': ['ADP', 'SCONJ', 'PART']}, 'OP': '?'},  # Preposição, conjunção ou partícula opcional (ex: "de", "que", "para")
      {'POS': 'DET', 'OP': '?'},  # Determinante opcional (ex: "um", "uma", "o", "a")
      {'POS': {'IN': ['NOUN', 'ADJ']}, 'OP': '?'},  # Substantivo opcional (ex: "marra", "casa", "guerreiro")
      {'POS': 'VERB', 'MORPH': 'VerbForm=Inf', 'OP': '?'},  # Verbo no infinitivo opcional (ex: "viajar", "falar")
  ]

  nomeauxverbo = [
      {"ENT_TYPE": "PER",'POS': 'PROPN', "MORPH": {"IN": [gender_morph]}},
      {'POS': 'ADV', 'OP': '?'},  # Provavelmente etc
      {'POS': 'ADV', 'OP': '?'},  # Negação
      {"POS":"VERB", 'OP': '?'},
      {'POS': 'AUX'},  # Verbo auxiliar
      {"POS":"VERB", 'OP': '?'},
      {'POS': 'AUX', 'OP': '?'},  # Verbo auxiliar para casos do tipo ela está ficando
      {'POS': 'ADV', 'OP': '?'},  # Realmente / Provavelmente
      {'POS': 'ADV', 'OP': '?'},  # Muito / Pouco
      {'POS': 'VERB', 'MORPH': {'IN': [f"{gender_morph}|VerbForm=Part|Voice=Pass"]}},  # Verbo na Voz Passiva
      {'POS': {'IN': ['ADP', 'SCONJ', 'PART']}, 'OP': '?'},  # Preposição, conjunção ou partícula opcional (ex: "de", "que", "para")
      {'POS': 'DET', 'OP': '?'},  # Determinante opcional (ex: "um", "uma", "o", "a")
      {'POS': {'IN': ['NOUN', 'ADJ']}, 'OP': '?'},  # Substantivo opcional (ex: "marra", "casa", "guerreiro")
      {'POS': 'VERB', 'MORPH': 'VerbForm=Inf', 'OP': '?'},  # Verbo no infinitivo opcional (ex: "viajar", "falar")
  ]

  matcher.add('sujeitoauxadjetivo', patterns=[sujeitoauxadjetivo])
  matcher.add('nomeauxproprio', patterns=[nomeauxproprio])
  matcher.add('sujeitoauxsubst', patterns=[sujeitoauxsubst])
  matcher.add('nomeauxsubst', patterns=[nomeauxsubst])
  matcher.add('sujeitoauxverbo', patterns=[sujeitoauxverbo])
  matcher.add('nomeauxverbo', patterns=[nomeauxverbo])

  return matcher

In [17]:
sujeitos_femininos = ["mulher", "mulheres", "ela", "elas", "menina", "meninas", "garota", "garotas", "senhora", "senhoras", "senhorita", "senhoritas", "moça", "moças", "donzela", "donzelas", "dama", "damas", "rainha", "rainhas", "esposa", "esposas", "namorada", "namoradas", "mina", "minas", "mãe", "mães", "filha", "filhas", "tia", "tias", "avó", "avós", "neta", "netas", "sobrinha", "sobrinhas", "madrasta", "madrastas", "entendeada", "entedeadas", "musa", "musas", "diva", "divas", "deusa", "deusas", "querida", "queridas", "princesa", "princesas"]
sujeitos_masculinos = ["homem", "homens", "ele", "eles", "menino", "meninos", "garoto", "garotos", "senhor", "senhores", "rapaz", "rapazes", "moço", "moços", "cavalheiro", "cavalheiros", "rei", "reis", "marido", "maridos", "namorado", "namorados", "novinho", "novinhos"]

In [18]:
male_matcher = define_pattern(sujeitos_masculinos, "Masc")
female_matcher = define_pattern(sujeitos_femininos, "Fem")

In [19]:
# Percorre frases_df. Pega o conteúdo de frase e aplica o matcher. 
# Caso tenha algum match, poe o valor em uma nova coluna chamada "tem_padrao" e guarda o valor do match em outra coluna chamada "padrao_encontrado"

def apply_matchers(frases_df, male_matcher, female_matcher):
    have_pattern = []
    pattern_found = []
    for index, row in frases_df.iterrows():
        if index % 1000 == 0:
            print(f"Processing index: {index}")
        doc = pln(row['frase'])
        male_matches = male_matcher(doc)
        female_matches = female_matcher(doc)
        if male_matches:
            have_pattern.append("Male")
            pattern_found.append(male_matches)
        elif female_matches:
            have_pattern.append("Female")
            pattern_found.append(female_matches)
        else:
            have_pattern.append("None")
            pattern_found.append(None)
    frases_df['tem_padrao'] = have_pattern
    frases_df['padrao_encontrado'] = pattern_found
    return frases_df
filtered_frases_df = apply_matchers(filtered_frases_df, male_matcher, female_matcher)
filtered_frases_df

Processing index: 0
Processing index: 1000
Processing index: 2000
Processing index: 3000
Processing index: 4000
Processing index: 5000
Processing index: 6000
Processing index: 7000
Processing index: 8000
Processing index: 9000
Processing index: 10000
Processing index: 11000
Processing index: 12000
Processing index: 13000
Processing index: 14000
Processing index: 15000
Processing index: 16000
Processing index: 17000
Processing index: 18000
Processing index: 19000
Processing index: 20000
Processing index: 21000
Processing index: 22000
Processing index: 23000
Processing index: 24000
Processing index: 25000
Processing index: 26000
Processing index: 27000
Processing index: 28000
Processing index: 29000
Processing index: 30000
Processing index: 31000
Processing index: 32000
Processing index: 33000
Processing index: 34000
Processing index: 35000
Processing index: 36000
Processing index: 37000
Processing index: 38000
Processing index: 39000
Processing index: 40000
Processing index: 41000
Processing index: 42000
Processing index: 43000
Processing index: 44000
Processing index: 45000
Processing index: 46000
Processing index: 47000
Processing index: 48000
Processing index: 49000
Processing index: 50000
Processing index: 51000
Processing index: 52000
Processing index: 53000
Processing index: 54000
Processing index: 55000
Processing index: 56000
Processing index: 57000
Processing index: 58000
Processing index: 59000
Processing index: 60000
Processing index: 61000
Processing index: 62000
Processing index: 63000
Processing index: 64000
Processing index: 65000
Processing index: 66000
Processing index: 67000
Processing index: 68000
Processing index: 69000
Processing index: 70000
Processing index: 71000
Processing index: 72000
Processing index: 73000
Processing index: 74000
Processing index: 75000
Processing index: 76000
Processing index: 77000
Processing index: 78000
Processing index: 79000
Processing index: 80000
Processing index: 81000
Processing index: 82000
Processing index: 83000
Processing index: 84000
Processing index: 85000
Processing index: 86000
Processing index: 87000
Processing index: 88000
Processing index: 89000
Processing index: 90000
Processing index: 91000
Processing index: 92000
Processing index: 93000
Processing index: 94000
Processing index: 95000
Processing index: 96000
Processing index: 97000
Processing index: 98000
Processing index: 99000
Processing index: 100000
Processing index: 101000
Processing index: 102000
Processing index: 103000
Processing index: 104000
Processing index: 105000
Processing index: 106000
Processing index: 107000
Processing index: 108000
Processing index: 109000
Processing index: 110000
Processing index: 111000
Processing index: 112000
Processing index: 113000
Processing index: 114000
Processing index: 115000
Processing index: 116000
Processing index: 117000
Processing index: 118000
Processing index: 119000
Processing index: 120000
Processing index: 121000
Processing index: 122000
Processing index: 123000
Processing index: 124000
Processing index: 125000
Processing index: 126000
Processing index: 127000
Processing index: 128000
Processing index: 129000
Processing index: 130000
Processing index: 131000
Processing index: 132000
Processing index: 133000
Processing index: 134000
Processing index: 135000
Processing index: 136000
Processing index: 137000
Processing index: 138000
Processing index: 139000
Processing index: 140000
Processing index: 141000
Processing index: 142000
Processing index: 143000
Processing index: 144000
Processing index: 145000
Processing index: 146000
Processing index: 147000
Processing index: 148000
Processing index: 149000
Processing index: 150000
Processing index: 151000
Processing index: 152000
Processing index: 153000
Processing index: 154000
Processing index: 155000
Processing index: 156000
Processing index: 157000
Processing index: 158000
Processing index: 159000
Processing index: 160000
Processing index: 161000
Processing index: 162000
Processing index: 163000
Processing index: 164000
Processing index: 165000
Processing index: 166000
Processing index: 167000
Processing index: 168000
Processing index: 169000
Processing index: 170000
Processing index: 171000
Processing index: 172000
Processing index: 173000
Processing index: 174000
Processing index: 175000
Processing index: 176000
Processing index: 177000
Processing index: 178000
Processing index: 179000
Processing index: 180000
Processing index: 181000
Processing index: 182000
Processing index: 183000
Processing index: 184000
Processing index: 185000
Processing index: 186000
Processing index: 187000
Processing index: 188000
Processing index: 189000
Processing index: 190000
Processing index: 191000
Processing index: 192000
Processing index: 193000
Processing index: 194000
Processing index: 195000
Processing index: 196000
Processing index: 197000
Processing index: 198000
Processing index: 199000
Processing index: 200000
Processing index: 201000
Processing index: 202000
Processing index: 203000
Processing index: 204000
Processing index: 205000
Processing index: 206000
Processing index: 207000
Processing index: 208000
Processing index: 209000
Processing index: 210000
Processing index: 211000
Processing index: 212000
Processing index: 213000
Processing index: 214000
Processing index: 215000
Processing index: 216000
Processing index: 217000
Processing index: 218000
Processing index: 219000
Processing index: 220000
Processing index: 221000
Processing index: 222000
Processing index: 223000
Processing index: 224000
Processing index: 225000
Processing index: 226000
Processing index: 227000
Processing index: 228000
Processing index: 229000
Processing index: 230000
Processing index: 231000
Processing index: 232000
Processing index: 233000
Processing index: 234000
Processing index: 235000
Processing index: 236000
Processing index: 237000
Processing index: 238000
Processing index: 239000
Processing index: 240000
Processing index: 241000
Processing index: 242000
Processing index: 243000
Processing index: 244000
Processing index: 245000
Processing index: 246000
Processing index: 247000
Processing index: 248000
Processing index: 249000
Processing index: 250000
Processing index: 251000
Processing index: 252000
Processing index: 253000
Processing index: 254000
Processing index: 255000
Processing index: 256000
Processing index: 257000
Processing index: 258000
Processing index: 259000
Processing index: 260000
Processing index: 261000
Processing index: 262000
Processing index: 263000
Processing index: 264000
Processing index: 265000
Processing index: 266000
Processing index: 267000
Processing index: 268000
Processing index: 269000
Processing index: 270000
Processing index: 271000
Processing index: 272000
Processing index: 273000
Processing index: 274000
Processing index: 275000
Processing index: 276000
Processing index: 277000
Processing index: 278000
Processing index: 279000
Processing index: 280000
Processing index: 281000
Processing index: 282000
Processing index: 283000
Processing index: 284000
Processing index: 285000
Processing index: 286000
Processing index: 287000
Processing index: 288000
Processing index: 289000
Processing index: 290000
Processing index: 291000
Processing index: 292000
Processing index: 293000
Processing index: 294000
Processing index: 295000
Processing index: 296000
Processing index: 297000
Processing index: 298000
Processing index: 299000
Processing index: 300000
Processing index: 301000
Processing index: 302000
Processing index: 303000
Processing index: 304000
Processing index: 305000
Processing index: 306000
Processing index: 307000
Processing index: 308000
Processing index: 309000
Processing index: 310000
Processing index: 311000
Processing index: 312000
Processing index: 313000
Processing index: 314000
Processing index: 315000
Processing index: 316000
Processing index: 317000
Processing index: 318000
Processing index: 319000
Processing index: 320000
Processing index: 321000
Processing index: 322000
Processing index: 323000
Processing index: 324000
Processing index: 325000
Processing index: 326000
Processing index: 327000
Processing index: 328000
Processing index: 329000
Processing index: 330000
Processing index: 331000
Processing index: 332000
Processing index: 333000
Processing index: 334000
Processing index: 335000
Processing index: 336000
Processing index: 337000
Processing index: 338000
Processing index: 339000
Processing index: 340000
Processing index: 341000
Processing index: 342000
Processing index: 343000
Processing index: 344000
Processing index: 345000
Processing index: 346000
Processing index: 347000
Processing index: 348000
Processing index: 349000
Processing index: 350000
Processing index: 351000
Processing index: 352000
Processing index: 353000
Processing index: 354000
Processing index: 355000
Processing index: 356000
Processing index: 357000
Processing index: 358000
Processing index: 359000
Processing index: 360000
Processing index: 361000
Processing index: 362000
Processing index: 363000
Processing index: 364000
Processing index: 365000
Processing index: 366000
Processing index: 367000
Processing index: 368000
Processing index: 369000
Processing index: 370000
Processing index: 371000
Processing index: 372000
Processing index: 373000
Processing index: 374000
Processing index: 375000
Processing index: 376000
Processing index: 377000
Processing index: 378000
Processing index: 379000
Processing index: 380000
Processing index: 381000
Processing index: 382000
Processing index: 383000
Processing index: 384000
Processing index: 385000
Processing index: 386000
Processing index: 387000
Processing index: 388000
Processing index: 389000
Processing index: 390000
Processing index: 391000
Processing index: 392000
Processing index: 393000
Processing index: 394000
Processing index: 395000
Processing index: 396000
Processing index: 397000
Processing index: 398000
Processing index: 399000
Processing index: 400000
Processing index: 401000
Processing index: 402000
Processing index: 403000
Processing index: 404000
Processing index: 405000
Processing index: 406000
Processing index: 407000
Processing index: 408000
Processing index: 409000
Processing index: 410000
Processing index: 411000
Processing index: 412000
Processing index: 413000
Processing index: 414000
Processing index: 415000
Processing index: 416000
Processing index: 417000
Processing index: 418000
Processing index: 419000
Processing index: 420000
Processing index: 421000
Processing index: 422000
Processing index: 423000
Processing index: 424000
Processing index: 425000
Processing index: 426000
Processing index: 427000
Processing index: 428000
Processing index: 429000
Processing index: 430000
Processing index: 431000
Processing index: 432000
Processing index: 433000
Processing index: 434000
Processing index: 435000
Processing index: 436000
Processing index: 437000
Processing index: 438000
Processing index: 439000
Processing index: 440000
Processing index: 441000
Processing index: 442000
Processing index: 443000
Processing index: 444000
Processing index: 445000
Processing index: 446000
Processing index: 447000
Processing index: 448000
Processing index: 449000
Processing index: 450000
Processing index: 451000
Processing index: 452000
Processing index: 453000
Processing index: 454000
Processing index: 455000
Processing index: 456000
Processing index: 457000
Processing index: 458000
Processing index: 459000
Processing index: 460000
Processing index: 461000
Processing index: 462000
Processing index: 463000
Processing index: 464000
Processing index: 465000
Processing index: 466000
Processing index: 467000
Processing index: 468000
Processing index: 469000
Processing index: 470000
Processing index: 471000
Processing index: 472000
Processing index: 473000
Processing index: 474000
Processing index: 475000
Processing index: 476000
Processing index: 477000
Processing index: 478000
Processing index: 479000
Processing index: 480000
Processing index: 481000
Processing index: 482000
Processing index: 483000
Processing index: 484000
Processing index: 485000
Processing index: 486000
Processing index: 487000
Processing index: 488000
Processing index: 489000
Processing index: 490000
Processing index: 491000
Processing index: 492000
Processing index: 493000
Processing index: 494000
Processing index: 495000
Processing index: 496000
Processing index: 497000
Processing index: 498000
Processing index: 499000
Processing index: 500000
Processing index: 501000
Processing index: 502000
Processing index: 503000
Processing index: 504000
Processing index: 505000
Processing index: 506000
Processing index: 507000
Processing index: 508000
Processing index: 509000
Processing index: 510000
Processing index: 511000
Processing index: 512000
Processing index: 513000
Processing index: 514000
Processing index: 515000
Processing index: 516000
Processing index: 517000
Processing index: 518000
Processing index: 519000
Processing index: 520000
Processing index: 521000
Processing index: 522000
Processing index: 523000
Processing index: 524000
Processing index: 525000
Processing index: 526000
Processing index: 527000
Processing index: 528000
Processing index: 529000
Processing index: 530000
Processing index: 531000
Processing index: 532000
Processing index: 533000
Processing index: 534000
Processing index: 535000
Processing index: 536000
Processing index: 537000
Processing index: 538000
Processing index: 539000
Processing index: 540000
Processing index: 541000
Processing index: 542000
Processing index: 543000
Processing index: 544000
Processing index: 545000
Processing index: 546000
Processing index: 547000
Processing index: 548000
Processing index: 549000
Processing index: 550000
Processing index: 551000
Processing index: 552000
Processing index: 553000
Processing index: 554000
Processing index: 555000
Processing index: 556000
Processing index: 557000
Processing index: 558000
Processing index: 559000
Processing index: 560000
Processing index: 561000
Processing index: 562000
Processing index: 563000
Processing index: 564000
Processing index: 565000
Processing index: 566000
Processing index: 567000
Processing index: 568000
Processing index: 569000
Processing index: 570000
Processing index: 571000
Processing index: 572000
Processing index: 573000
Processing index: 574000
Processing index: 575000
Processing index: 576000
Processing index: 577000
Processing index: 578000
Processing index: 579000
Processing index: 580000
Processing index: 581000
Processing index: 582000
Processing index: 583000
Processing index: 584000
Processing index: 585000
Processing index: 586000
Processing index: 587000
Processing index: 588000
Processing index: 589000
Processing index: 590000
Processing index: 591000
Processing index: 592000
Processing index: 593000
Processing index: 594000
Processing index: 595000
Processing index: 596000
Processing index: 597000
Processing index: 598000
Processing index: 599000
Processing index: 600000
Processing index: 601000
Processing index: 602000
Processing index: 603000
Processing index: 604000
Processing index: 605000
Processing index: 606000
Processing index: 607000
Processing index: 608000
Processing index: 609000
Processing index: 610000
Processing index: 611000
Processing index: 612000
Processing index: 613000
Processing index: 614000
Processing index: 615000
Processing index: 616000
Processing index: 617000
Processing index: 618000
Processing index: 619000
Processing index: 620000
Processing index: 621000
Processing index: 622000
Processing index: 623000
Processing index: 624000
Processing index: 625000
Processing index: 626000
Processing index: 627000
Processing index: 628000
Processing index: 629000
Processing index: 630000
Processing index: 631000
Processing index: 632000
Processing index: 633000
Processing index: 634000
Processing index: 635000
Processing index: 636000
Processing index: 637000
Processing index: 638000
Processing index: 639000
Processing index: 640000
Processing index: 641000
Processing index: 642000
Processing index: 643000
Processing index: 644000
Processing index: 645000
Processing index: 646000
Processing index: 647000
Processing index: 648000
Processing index: 649000
Processing index: 650000
Processing index: 651000
Processing index: 652000
Processing index: 653000
Processing index: 654000
Processing index: 655000
Processing index: 656000
Processing index: 657000
Processing index: 658000
Processing index: 659000
Processing index: 660000
Processing index: 661000
Processing index: 662000
Processing index: 663000
Processing index: 664000
Processing index: 665000
Processing index: 666000
Processing index: 667000
Processing index: 668000
Processing index: 669000
Processing index: 670000
Processing index: 671000
Processing index: 672000
Processing index: 673000
Processing index: 674000
Processing index: 675000
Processing index: 676000
Processing index: 677000
Processing index: 678000
Processing index: 679000
Processing index: 680000
Processing index: 681000
Processing index: 682000
Processing index: 683000
Processing index: 684000
Processing index: 685000
Processing index: 686000
Processing index: 687000
Processing index: 688000
Processing index: 689000
Processing index: 690000
Processing index: 691000
Processing index: 692000
Processing index: 693000
Processing index: 694000
Processing index: 695000
Processing index: 696000
Processing index: 697000
Processing index: 698000
Processing index: 699000
Processing index: 700000
Processing index: 701000
Processing index: 702000
Processing index: 703000
Processing index: 704000
Processing index: 705000
Processing index: 706000
Processing index: 707000
Processing index: 708000
Processing index: 709000
Processing index: 710000
Processing index: 711000
Processing index: 712000
Processing index: 713000
Processing index: 714000
Processing index: 715000
Processing index: 716000
Processing index: 717000
Processing index: 718000
Processing index: 719000
Processing index: 720000
Processing index: 721000
Processing index: 722000
Processing index: 723000
Processing index: 724000
Processing index: 725000
Processing index: 726000
Processing index: 727000
Processing index: 728000
Processing index: 729000
Processing index: 730000
Processing index: 731000
Processing index: 732000
Processing index: 733000
Processing index: 734000
Processing index: 735000
Processing index: 736000
Processing index: 737000
Processing index: 738000
Processing index: 739000
Processing index: 740000
Processing index: 741000
Processing index: 742000
Processing index: 743000
Processing index: 744000
Processing index: 745000
Processing index: 746000
Processing index: 747000
Processing index: 748000
Processing index: 749000
Processing index: 750000
Processing index: 751000
Processing index: 752000
Processing index: 753000
Processing index: 754000
Processing index: 755000
Processing index: 756000
Processing index: 757000
Processing index: 758000
Processing index: 759000
Processing index: 760000
Processing index: 761000
Processing index: 762000
Processing index: 763000
Processing index: 764000
Processing index: 765000
Processing index: 766000
Processing index: 767000
Processing index: 768000
Processing index: 769000
Processing index: 770000
Processing index: 771000
Processing index: 772000
Processing index: 773000
Processing index: 774000
Processing index: 775000
Processing index: 776000
Processing index: 777000
Processing index: 778000
Processing index: 779000
Processing index: 780000
Processing index: 781000
Processing index: 782000
Processing index: 783000
Processing index: 784000
Processing index: 785000
Processing index: 786000
Processing index: 787000
Processing index: 788000
Processing index: 789000
Processing index: 790000
Processing index: 791000
Processing index: 792000
Processing index: 793000
Processing index: 794000
Processing index: 795000
Processing index: 796000
Processing index: 797000
Processing index: 798000
Processing index: 799000
Processing index: 800000
Processing index: 801000
Processing index: 802000
Processing index: 803000

,music_id,music_frase_id,frase,frase_id,tem_padrao,padrao_encontrado
0,1,1,Carolina é uma menina bem difícil de esquecer.,1,Female,"[(1916877163388338700, 3, 6), (191687716338833..."
1,1,2,Andar bonito e um brilho no olhar.,2,None,None
2,1,3,Tem um jeito adolescente que me faz enlouquecer.,3,None,None
3,1,4,E um molejo que eu não vou te enganar.,4,None,None
4,1,5,"Maravilha feminina, meu docinho de pavê.",5,None,None
...,...,...,...,...,...,...
2685690,146609,480,Recite as afirmações por 10 minutos ininterrup...,4574304,None,None
2685691,146611,4,Chove sem parar\n.,4574434,None,None
2685692,146611,10,De molhar o meu divino amor\n.,4574440,None,None
2685693,146611,14,Inocente como a flor\n.,4574444,None,None
2685694,146611,18,O meu amor assim\n.,4574448,None,None

In [20]:
filtered_frases_df.to_csv('data/frases-musicas-final.csv', index=False)