In [1]:
import pandas as pd

In [5]:
full_file_path = "data/frases-musicas-final-filled.csv"
minimal_file_path = "data/frases-musicas-final-minimal.csv"
assignments_file_path = "data/assignments_second_round.csv"

In [3]:
df = pd.read_csv(full_file_path)
df.columns

Index(['music_id', 'music_frase_id', 'frase', 'frase_id', 'tem_padrao',
       'padrao_encontrado'],
      dtype='object')

In [9]:
df

,music_id,music_frase_id,frase,frase_id,tem_padrao,padrao_encontrado
0,1,1,Carolina é uma menina bem difícil de esquecer.,1,Female,"[(1916877163388338700, 3, 6), (191687716338833..."
1,1,2,Andar bonito e um brilho no olhar.,2,N,NaN
2,1,3,Tem um jeito adolescente que me faz enlouquecer.,3,N,NaN
3,1,4,E um molejo que eu não vou te enganar.,4,N,NaN
4,1,5,"Maravilha feminina, meu docinho de pavê.",5,N,NaN
...,...,...,...,...,...,...
2685690,146609,480,Recite as afirmações por 10 minutos ininterrup...,4574304,N,NaN
2685691,146611,4,Chove sem parar\n.,4574434,N,NaN
2685692,146611,10,De molhar o meu divino amor\n.,4574440,N,NaN
2685693,146611,14,Inocente como a flor\n.,4574444,N,NaN
2685694,146611,18,O meu amor assim\n.,4574448,N,NaN

In [7]:
assignments_df = pd.read_csv(assignments_file_path)
assignments_df

       frase_id annotator_id
0        594474       user01
1        594474       user02
2         32675       user02
3         32675       user03
4       3362704       user03
...         ...          ...
32327     98857       user17
32328    487639       user16
32329    487639       user18
32330   3478220       user17
32331   3478220       user19

[32332 rows x 2 columns]

In [8]:
assigned_phrase_ids = assignments_df['frase_id'].unique()
reduced_df = df[df['frase_id'].isin(assigned_phrase_ids)]
reduced_df

,music_id,music_frase_id,frase,frase_id,tem_padrao,padrao_encontrado
0,1,1,Carolina é uma menina bem difícil de esquecer.,1,Female,"[(1916877163388338700, 3, 6), (191687716338833..."
5,1,6,"Inteligente, ela é muito sensual.",6,Female,"[(1916877163388338700, 2, 6)]"
33,1,51,"Menina bela, menina bela.",51,Female,"[(1916877163388338700, 0, 2), (191687716338833..."
456,18,12,Ele não é feliz.,798,Male,"[(1916877163388338700, 0, 4)]"
648,25,23,"Ela é linda, mas não tem nome.",1235,Female,"[(1916877163388338700, 0, 3)]"
...,...,...,...,...,...,...
2685117,146601,213,Abaixo do céu todo homem é igual.,4572368,Male,"[(1916877163388338700, 4, 7)]"
2685218,146604,31,Embora a inteligência do homem seja grande par...,4572851,Male,"[(1916877163388338700, 4, 7), (191687716338833..."
2685250,146604,70,Para ser compassivo antes precisa da consciênc...,4572890,Female,"[(1916877163388338700, 11, 13)]"
2685383,146605,50,O homem mentalmente espiritualizado é falante.,4573057,Male,"[(1916877163388338700, 1, 4)]"
2685409,146607,1,"O homem atual, na grande maioria, é carente da...",4573086,Male,"[(1916877163388338700, 1, 3)]"

In [10]:
reduced_df[['frase_id', 'frase']].to_csv(minimal_file_path, index=False)